# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "virtio_pci" "xhci_pci" "sr_mod" "virtio_blk" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-label/root";
      fsType = "ext4";
    };
  # fileSystems."/home" =
  #   { device = "/dev/disk/by-label/home";
  #     fsType = "exfat";
  #   };

  # hardware.bluetooth = {
  # 	enable = true;
  # 	powerOnBoot = true;
  # };

  # hardware.graphics.enable =  true; # enable opengl
  # hardware.opentabletdriver.enable = true; # enable drawing tablet

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
